import type { AccountRow, AuthTaskRow, ChatType, DirectChatListRow, DailyEntry, GroupDefaults, GroupListRow, GroupMemberRow, GroupPatch, GroupRow, InsertMessageInput, MemberRow, MemoryDocuments, MemoryDocType, MemoryScopeType, MessageRow, OutboxRow, PublicAccountRow, QQChatRuntimeSettings, QQMediaKind, QQQuoteIndexInput, QQQuoteIndexRow, StoredAttachmentSummary, ReflectionTaskInput } from '../types.js';
export declare class QQChatDatabase {
    readonly path: string;
    private readonly db;
    constructor(path: string);
    close(): void;
    private migrate;
    private migrateMemberProfiles;
    private normalizeDailyDocuments;
    pruneAuthTasks(): void;
    saveAuthTask(taskId: string, aesKey: string, ttlMs?: number): void;
    getAuthTask(taskId: string): AuthTaskRow | undefined;
    deleteAuthTask(taskId: string): void;
    upsertAccount(appId: string, secret: string, sandbox?: boolean): AccountRow;
    accountByAppId(appId: string): AccountRow | undefined;
    accountById(id: number): AccountRow | undefined;
    firstEnabledAccount(): AccountRow | undefined;
    enabledAccounts(): AccountRow[];
    publicAccounts(): PublicAccountRow[];
    setAccountGateway(id: number, status: AccountRow['gateway_status'], error?: string | null, botUserId?: string): void;
    setAccountEnabled(id: number, enabled: boolean): void;
    getSetting<T>(key: string, fallback: T): T;
    setSetting(key: string, value: unknown): void;
    runtimeSettings(defaults: QQChatRuntimeSettings): QQChatRuntimeSettings;
    upsertGroup(accountId: number, platformGroupId: string, defaults?: GroupDefaults): GroupRow;
    groupByPlatform(accountId: number, platformGroupId: string): GroupRow | undefined;
    groupById(id: number): GroupRow | undefined;
    updateGroup(id: number, patch: GroupPatch): GroupRow | undefined;
    saveQuoteIndex(input: QQQuoteIndexInput): void;
    quoteIndex(accountId: number, chatType: ChatType, chatId: string, msgIdx: string): QQQuoteIndexRow | undefined;
    expireQuoteIndex(before: number): number;
    listGroups(): GroupListRow[];
    listDirectChats(): DirectChatListRow[];
    listKnownMembers(): MemberRow[];
    upsertMember(accountId: number, platformUserId: string, displayName?: string): MemberRow;
    memberByPlatform(accountId: number, platformUserId: string): MemberRow | undefined;
    memberById(id: number): MemberRow | undefined;
    touchGroupMember(groupId: number, memberId: number, displayName?: string): void;
    listGroupMembers(groupId: number): GroupMemberRow[];
    addGroupMemberNickname(groupId: number, memberId: number, nickname: string): void;
    insertMessage(input: InsertMessageInput): number;
    private linkMessageAttachments;
    saveAttachment(input: {
        id: string;
        accountId: number;
        sourceMessageId?: string;
        sourceFileId?: string;
        kind: QQMediaKind;
        filename: string;
        contentType?: string;
        sizeBytes: number;
        localPath?: string;
        imageRef?: StoredAttachmentSummary['imageRef'];
        expiresAt?: number;
    }): void;
    attachmentById(id: string): StoredAttachmentSummary | undefined;
    findReusableAttachment(accountId: number, sourceMessageId: string, sourceFileId?: string, kind?: QQMediaKind): StoredAttachmentSummary | undefined;
    extendAttachment(id: string, expiresAt: number): void;
    attachmentForSession(sessionId: string, attachmentId: string): StoredAttachmentSummary | undefined;
    expireAttachments(before: number): number;
    expiredAttachmentPaths(before: number): string[];
    markAttachmentDeleted(path: string): void;
    listMessages(groupId: number, limit?: number): MessageRow[];
    listDirectMessages(memberId: number, limit?: number): MessageRow[];
    groupBySession(sessionId: string): GroupRow | undefined;
    memberBySession(sessionId: string): MemberRow | undefined;
    recentGroupMessages(groupId: number, limit?: number): MessageRow[];
    unreflectedMessages(groupId: number, limit?: number): MessageRow[];
    unreflectedCount(groupId: number): number;
    unreflectedMemberMessages(groupId: number, limit?: number): MessageRow[];
    unreflectedMemberCount(groupId: number): number;
    markReflected(groupId: number, messageId: number): void;
    markMembersReflected(groupId: number, messageId: number): void;
    startReflectionTask(input: ReflectionTaskInput): boolean;
    finishReflectionTask(idempotencyKey: string, status: 'completed' | 'failed'): void;
    memoryDocs(scopeType: MemoryScopeType, scopeKey: number): MemoryDocuments;
    setMemoryDoc(scopeType: MemoryScopeType, scopeKey: number, docType: MemoryDocType, content: string): void;
    appendMemoryDoc(scopeType: MemoryScopeType, scopeKey: number, docType: MemoryDocType, content: string, maxChars?: number): void;
    appendDailyDoc(scopeType: MemoryScopeType, scopeKey: number, date: string, note: string, maxChars?: number): void;
    dailyEntries(scopeType: MemoryScopeType, scopeKey: number): DailyEntry[];
    setDailyEntries(scopeType: MemoryScopeType, scopeKey: number, entries: DailyEntry[]): void;
    getChatSession(chatType: ChatType, rowId: number): string | null;
    setChatSession(chatType: ChatType, rowId: number, sessionId: string): void;
    queueOutbox(accountId: number, chatType: ChatType, targetId: string, content: string, scheduledAt?: number): number;
    dueOutbox(limit?: number): OutboxRow[];
    finishOutbox(id: number, error?: string | null): void;
}
