import type { Context } from '@deepseek-ai/cordis';
import type { ContentBlock } from '@deepseek-ai/dsh-llm';
import type { Session, SessionEvent } from '@deepseek-ai/dsh-session';
import '../shared/augmentations.js';
import type { QQChatDatabase } from '../storage/db.js';
import type { MemoryEngine } from '../storage/memory.js';
import type { ChatType, GroupRow, LoggerLike, MemberRow, StoredAttachmentSummary, QQChatConfig, QQChatDisplayEvent, QQNormalizedMessage } from '../types.js';
export declare function resolveQQSessionPreset(header: Session['header'], events: readonly SessionEvent[]): string | undefined;
export declare class DshQQBridge {
    private readonly ctx;
    private readonly db;
    private readonly memory;
    private readonly config;
    private readonly logger;
    private readonly handles;
    private readonly locks;
    private readonly pending;
    private readonly routes;
    private readonly selections;
    private readonly pendingResets;
    private readonly activeActors;
    private readonly activeAttachments;
    private readonly activeMediaReadable;
    private readonly memorySnapshots;
    private readonly disposeEvent;
    private readonly disposeAssistantStream;
    private readonly disposeToolGate;
    private readonly disposeCommands;
    private readonly disposeImageTool;
    private readonly disposeMediaTools;
    constructor(ctx: Context, db: QQChatDatabase, memory: MemoryEngine, config: QQChatConfig, logger?: LoggerLike);
    attachMappedSessionsToWorkspace(): Promise<void>;
    dispose(): Promise<void>;
    ensureChatSession(chatType: ChatType, row: GroupRow | MemberRow): Promise<string>;
    recordTranscript(event: QQChatDisplayEvent, row: GroupRow | MemberRow, createSession?: boolean): Promise<string | undefined>;
    reply(message: QQNormalizedMessage, group: GroupRow | undefined, member: MemberRow, attachments?: StoredAttachmentSummary[], onTextDelta?: (delta: string) => void, isOwner?: boolean): Promise<string>;
    private onSessionEvent;
    private injectMemorySnapshot;
    private restoreMemorySnapshot;
    private ensureAgent;
    private isArchived;
    private attachToWorkspace;
    private rememberRoute;
    private appendDisplayIfMissing;
    private appendOwnerMessageIfMissing;
    private ensureTitle;
    private tryResume;
    private agentOptions;
    private ensureSelection;
    private selection;
    private requestReset;
    private resetSession;
    private commandHelp;
    private registerCommands;
    private modelCommand;
    private presetCommand;
    private statusCommand;
    private composition;
    private persistedPreset;
    private serial;
}
/** Build the durable DSH content for one QQ turn without pre-flighting the model. */
export declare function qqMessageContent(text: string, attachments: readonly StoredAttachmentSummary[]): ContentBlock[];
