import type { Context } from '@deepseek-ai/cordis';
import type { DshQQBridge } from './agent-bridge.js';
import type { QQChatDatabase } from '../storage/db.js';
import type { QQChatLogger } from '../shared/logging.js';
import type { MemoryEngine } from '../storage/memory.js';
import type { QQApiClient } from '../gateway/api.js';
import type { QQBindService } from '../gateway/auth.js';
import { QQGateway } from '../gateway/gateway.js';
import { QQMediaStore } from '../media/store.js';
import type { AccountRow, ChatTargetRow, ChatType, GroupReceiveMode, GroupRow, QQAttachmentInput, QQChatConfig, QQChatRuntimeSettings, QQChatRuntimeSettingsPatch, QQNormalizedMessage, StoredAttachmentSummary } from '../types.js';
export declare class QQChatRuntime {
    readonly ctx: Context;
    readonly db: QQChatDatabase;
    readonly api: QQApiClient;
    readonly auth: QQBindService;
    readonly memory: MemoryEngine;
    readonly bridge: DshQQBridge;
    readonly config: QQChatConfig;
    readonly logger: QQChatLogger;
    readonly media: QQMediaStore;
    readonly gateways: Map<number, QQGateway>;
    private outboxTimer?;
    private mediaCleanupTimer?;
    constructor(ctx: Context, db: QQChatDatabase, api: QQApiClient, auth: QQBindService, memory: MemoryEngine, bridge: DshQQBridge, config: QQChatConfig, logger: QQChatLogger, media: QQMediaStore);
    start(): Promise<void>;
    stop(): Promise<void>;
    settings(): QQChatRuntimeSettings;
    updateSettings(patch: QQChatRuntimeSettingsPatch): QQChatRuntimeSettings;
    listChats(): ChatTargetRow[];
    ensureChatSession(chatType: ChatType, rowId: number): Promise<string>;
    sendActive(chatType: ChatType, rowId: number, content: string): Promise<string>;
    readAttachment(sessionId: string, attachmentId: string): Promise<Record<string, unknown>>;
    startGateway(account: AccountRow | undefined): void;
    restartGateway(accountId: number): Promise<void>;
    connectManual(appId: string, appSecret: string, sandbox?: boolean): Promise<AccountRow>;
    private onIncoming;
    private chatRow;
    private flushOutbox;
}
export declare function shouldReplyToGroup(mode: GroupReceiveMode, group: Pick<GroupRow, 'enabled' | 'read_enabled'>, mentioned: boolean): boolean;
export declare function mergeIndexedQuote(message: QQNormalizedMessage, indexed: import('../types.js').QQQuoteIndexRow | undefined): QQNormalizedMessage;
export declare function indexAttachments(inputs: QQAttachmentInput[], stored: StoredAttachmentSummary[]): QQAttachmentInput[];
